version: '2.1'

networks:
  ddev_default:
    driver: bridge

services:

  mysql_db:
    image: 'percona:latest'
    container_name: 'mysql_db'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: DB_MYAPP
      MYSQL_USER: test_qa
      MYSQL_PASSWORD: qa_test
    ports:
      - '3306:3306'
    volumes:
      - '../mysql/myapp_db:/docker-entrypoint-initdb.d'
    networks:
      - ddev_default
    healthcheck:
      test: ['CMD', 'mysql', '-uroot', '-padmin', '-h0.0.0.0', '-P3306']
      timeout: 2s
      retries: 15

  mock:
    build:
      context: '../mock'
      dockerfile: 'mockerfile'
    image: 'vk_api'
    container_name: 'mock'
    networks:
      - ddev_default
    ports:
      - '9000:9000'

  myapp:
    image: 'myapp'
    container_name: 'myapp'
    volumes:
      - '../:/project'
    ports:
      - '9999:9999'
    links:
      - 'mock:mock'
      - 'mysql_db:mysql_db'
    command: ['/app/myapp', '--config=/project/application/myapp.conf']
    networks:
      - ddev_default
    depends_on:
      mysql_db:
        condition: service_healthy